[package]
name = "xylkit"
version = "0.1.0"
authors = ["Xylkit Team"]

[addresses]
xylkit = "_"

[dev-addresses]
xylkit = "0x42"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
